version: "3.7"

services:
  database:
    image: postgres:12

    environment:
      - POSTGRES_USER=younes
      - POSTGRES_PASSWORD=1234 
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    networks:
        - hidden
  nestjs:
    build : ./backend/.
    image: nestjs
    ports:
      - "3001:3001"
    networks:
        - hidden
    depends_on:
      - database
    volumes:
      - ./backend:/root/src/app

networks:
  hidden:
    name: hidden
    driver: bridge
